export const CATEGORIES = [
  "Tech Talk",
  "Life Hacks",
  "Creative Corner",
  "Foodie Adventures",
  "Pop Culture",
  "Music Vibes",
  "Travel Diaries",
  "Gaming World",
  "Inspiration",
  "Memes & Fun",
  "Health & Wellness",
  "DIY Projects",
  "Books & Reviews",
  "Art & Design",
  "Tech Tutorials",
  "Fashion Trends",
  "Beautify Yourself",
  "Home Decor",
  "Wedding Planning",
  "Baby Care",
  "Pet Lovers",
  "Sports News",
  "Business Tips",
  "Personal Finance",
  "Education",
  "History",
  "Science and Technology",
  "Environmental Issues",
  "Social Justice",
  "Philosophy",
  "Religion",
  "Politics",
  "Photography",
  "Videography",
  "Gardening",
  "Cooking",
]

