import { Toaster } from "@/components/ui/toaster"
import { SWRProvider } from "@/providers/swr-provider"
import type { Metadata } from "next"
import { Geist } from "next/font/google"
import "./globals.css"
import { NuqsAdapter } from "nuqs/adapters/next/app"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <SWRProvider>
          <NuqsAdapter>
            <div className="flex min-h-screen w-full max-sm:px-6 max-w-xl mx-auto !my-20">{children}</div>
            <Toaster />
          </NuqsAdapter>
        </SWRProvider>
      </body>
    </html>
  )
}
